// <auto-generated />
using System;
using MarginTrading.CommissionService.SqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarginTrading.CommissionService.SqlRepositories.Migrations
{
    [DbContext(typeof(CommissionDbContext))]
    partial class CommissionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("commission")
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarginTrading.CommissionService.SqlRepositories.Entities.KidScenarioEntity", b =>
                {
                    b.Property<string>("Isin")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<decimal?>("KidModerateScenario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KidModerateScenarioAvreturn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Isin");

                    b.ToTable("KidScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
